fix: Single/Plural words
thisdot/chainlink-docs pull request #21
Opened 2024-10-21 10:23 UTC by markshenouda

**IMPORTANT: Please do not create a Pull Request without creating an issue first.Any change needs to be discussed before proceeding.**

## Closing issues

closes #ISSUE_NUMBER_GOES_HERE

...

## Description

...

## Changes

- High level
- changes that
- you made
- ...

2024-10-21 11:24 UTC, Zelig880 requested changes

2024-10-21 11:24 UTC, Zelig880 commented on src/components/CCIP/Search/Search.tsx
> +                            {lane?.lane?.supportedTokens
This is incorrect.

before it would print "0 token", while now it just show "token if "supportedTokens i false, and it never checks if length is 0

2024-10-22 07:54 UTC, markshenouda commented on src/components/CCIP/Search/Search.tsx
> +                            {lane.lane.supportedTokens && Object.keys(lane.lane.supportedTokens).length > 1
Yeah it's in the next line 181

2024-10-22 11:18 UTC, Zelig880 commented on src/components/CCIP/Search/Search.tsx
> +                            {lane.lane.supportedTokens && Object.keys(lane.lane.supportedTokens).length > 1
I meant this `lane.lane.supportedTokens` should be changed with `lane?.lane?.supportedTokens`

2024-10-22 20:29 UTC, Zelig880 approved these changes

2024-10-22 20:29 UTC, merged